### ISSUE TITLE
Can not run through (Pyro 0.5.1)

### ISSUE THREAD

**Issue by cloudygoose** [nyu-dl/dl4dial-bayesian-calibration#1]
Hi, thanks for providing this tool, but I tried to run the default example, but got this error,
my pyro version is 0.5.1
```
python run.py --input-array ./mtbeam_human_eval.npz.npy --num-samples 50 --num-warmup-samples 100
warmup:   9%|███▋                                       | 13/150 [01:29, 10.90s/it, step size=5.00e-02, acc. prob=0.692]
sample: 100%|██████████████████████████████████████████| 150/150 [14:11,  5.68s/it, step size=2.98e-01, acc. prob=0.877]

Traceback (most recent call last):
  File "run.py", line 96, in <module>
    main()
  File "run.py", line 90, in main
    mean, std = infer(data, config)
  File "run.py", line 64, in infer
    score_marginal = pyro.infer.EmpiricalMarginal(mcmc_run, sites=["model-{}".format(mi) for mi in range(config['n_models'])])
  File "/data/sls/r/u/tianxing/home/anaconda2/envs/py3torch/lib/python3.6/site-packages/pyro/infer/abstract_infer.py", line 32, in __init__
    "trace_dist must be trace posterior distribution object"
AssertionError: trace_dist must be trace posterior distribution object
```

**Comment by kyunghyuncho** [comment]
@uralik

**Comment by cloudygoose** [comment]
Further, I guess the score doesn't have to be integers? (I can try to do a little hack myself)

**Comment by uralik** [comment]
Hi, thanks for your interest. This code should work with version 0.3.2

I will figure out what changed since then a bit later, for now please try with older version.

**Comment by cloudygoose** [comment]
Oh wait, I guess it would be easier that I just scale my scores to be integer, then I just change the prior in the code?

**Comment by cloudygoose** [comment]
The older version works, thanks!

**Comment by uralik** [comment]
> The older version works, thanks!

I am testing now with the new version, am I correct that actually the progress bar went to the end, i.e. the error happens after mcmc traces have been collected?

**Comment by uralik** [comment]
> Further, I guess the score doesn't have to be integers? (I can try to do a little hack myself)

> Oh wait, I guess it would be easier that I just scale my scores to be integer, then I just change the prior in the code?

Model's score (M_i) and observed score (S_{i,j}) both sampled from normal with different parameterization:
`pyro.sample("model-{}".format(mi), dist.Normal(mu_, 1.))`
`pyro.sample("scores", dist.Normal(mu_, 1.))`

So they do not need to be integers. However make sure that range for your model's mean parameter prior correspond to scale you use!

We also did such calibration for binary scores at some point, it is not included in this code. I pinged you in messenger where we can discuss this offline if you want.

**Comment by cloudygoose** [comment]
> > The older version works, thanks!
> 
> I am testing now with the new version, am I correct that actually the progress bar went to the end, i.e. the error happens after mcmc traces have been collected?

Yes, seems that way.

**Comment by uralik** [comment]
Okay right now they are in the process of migration to a new MCMC version not based on TracePosterior class with introduction of new `predictive` utility:

https://forum.pyro.ai/t/posterior-predictive-distribution-using-mcmc/783/9

They actively changing things for MCMC now and I will get back to this later (they say new changes will speed things up).

For now I will add the working version number in the Readme.
